# Generated by Django 2.2.1 on 2019-07-02 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата обновления')),
                ('status', models.SmallIntegerField(choices=[(0, 'Успешно'), (1, 'Имеются ошибки при обновлении')], verbose_name='Статус обновления')),
            ],
            options={
                'verbose_name': 'Плановое обновление',
                'verbose_name_plural': 'Плановые обновления',
            },
        ),
        migrations.CreateModel(
            name='ScheduledUpdateError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='Название города')),
                ('source', models.CharField(max_length=100, verbose_name='Название источника')),
                ('error', models.TextField(verbose_name='Текст ошибки')),
                ('scheduled_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ScheduledUpdate', verbose_name='Плановое обновление')),
            ],
            options={
                'verbose_name': 'Ошибка планового обновления',
                'verbose_name_plural': 'Ошибки плановых обновлений',
            },
        ),
    ]
